/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [
      "www.verywellmind.com",
      "cdn.psychologytoday.com",
      "media.npr.org",
      "scx2.b-cdn.net",
      "cdn.theatlantic.com",
      "thumbor.forbes.com",
      "ggsc.s3.amazonaws.com",
      "www.yourtango.com",
      "cdn.cnn.com",
      "i-cdn.embed.ly",
      "img.huffingtonpost.com",
      "static01.nyt.com",
      "images.unsplash.com",
      "www.newsmax.com",
      "1721181113.rsc.cdn77.org",
      "cdn.mindful.org",
      "greatergood.berkeley.edu",
      "api.time.com",
      "cdnph.upi.com",
      "adaa.org",
      "s3.amazonaws.com",
      "content.thriveglobal.com",
      "media.wired.com",
      "www.theladders.com",
      "image.cnbcfm.com",
      "imgix.bustle.com",
      "www.sunset.com",
      "images.wsj.net",
      "cdn.aarp.net",
      "media2.s-nbcnews.com",
      "chopracom.s3.us-west-1.amazonaws.com",
      "khn.org",
      "hhp-blog.s3.amazonaws.com",
      "media1.s-nbcnews.com",
      "www.naturalnews.com",
      "i0.wp.com",
      "www.newswise.com",
      "www.washingtonpost.com",
      "consciouslifenews.com",
      "wellbeingtrust.org",
      "static.scientificamerican.com",
      "www.chicagotribune.com",
      "s3.ap-southeast-1.amazonaws.com",
      "ideas.ted.com",
      "media3.s-nbcnews.com",
      "media.mercola.com",
      "globalnews.ca",
      "cdn-images-1.medium.com",
      "www.cdc.gov",
      "images.ctfassets.net",
    ],
  },
};

module.exports = nextConfig;
